<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="language" content="en" />
    <title>NOC Application - Index</title>
    <link rel="stylesheet" href="/noc/resources/css/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="/noc/resources/css/noc_style.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="/noc/resources/css/blueprint/print.css" type="text/css" media="print">
    <link rel="stylesheet" href="/noc/resources/css/blueprint/plugins/buttons/screen.css" type="text/css" media="print">
    <!--[if IE]><link rel="stylesheet" href="/noc/resources/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
</head>
<body>
    <div class="container">
        <div>
            <div id="zfHeader">
                <h1 class="logo">NOC Application</h1>
            </div>
        </div>
        <div>
            <div id="zfMenu">
                
                 <br/>

            </div>
            <div id="zfContent">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
        <br/>
        <div class="block">
            <div id="zfFooter">
                <p>Copyright &copy;</p>
            </div>
        </div>
    </div>
</body>
</html>
