<h2>List all of existing users</h2>

<p>
    <a href="<?= $this->url(array(
        'module'     => 'admin',
        'controller' => 'user',
        'action'     => 'add'
    )) ?>">Add New User</a>
</p>

<table>
    <thead>
        <!-- <th>id</th> -->
        <th>name</th>
        <th>username</th>
        <th>&nbsp;</th>
    </thead>
    <tbody>
    <?php FOREACH($this->users AS $user): ?>
        <tr>
            <!-- <td><?= $user->get('id');?></td> -->
            <td><?= $user->get('name');?></td>
            <td><?= $user->get('username');?></td>
            <td>
                <a href="<?= $this->url(array(
                            'module'     => 'admin',
                            'controller' => 'user',
                            'action'     => 'edit',
                            'id'         => $user->get('id')
                )) ?>">Edit</a>
                  |
                <a href="<?= $this->url(array(
                            'module'     => 'admin',
                            'controller' => 'user',
                            'action'     => 'delete',
                            'id'         => $user->get('id')
                )) ?>">Delete</a>
                  |
                <a href="<?= $this->url(array(
                            'module'     => 'admin',
                            'controller' => 'user',
                            'action'     => 'changepassword',
                            'id'         => $user->get('id')
                )) ?>">Change Pass</a>
            </td>
        </tr>
    <?php ENDFOREACH; ?>
    </tbody>
</table>
